# Staging 서버 세팅 (올인원)
---
- name: Staging 디렉토리 생성
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - /home/{{ ansible_user }}/tymee/staging
    - /home/{{ ansible_user }}/tymee/staging/nginx
    - /home/{{ ansible_user }}/tymee/staging/nginx/conf.d
    - /home/{{ ansible_user }}/tymee/staging/certbot/conf
    - /home/{{ ansible_user }}/tymee/staging/certbot/www

- name: docker-compose.yml 복사
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/tymee/staging/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: .env 파일 생성
  template:
    src: env.j2
    dest: /home/{{ ansible_user }}/tymee/staging/.env
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: nginx.conf 복사
  template:
    src: nginx.conf.j2
    dest: /home/{{ ansible_user }}/tymee/staging/nginx/nginx.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: nginx default.conf 복사
  template:
    src: default.conf.j2
    dest: /home/{{ ansible_user }}/tymee/staging/nginx/conf.d/default.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: GitHub Container Registry 로그인
  community.docker.docker_login:
    registry: ghcr.io
    username: "{{ github_username }}"
    password: "{{ github_token }}"
  become_user: "{{ ansible_user }}"
  when: github_token is defined and github_token != ""

- name: Staging 컨테이너 실행
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/tymee/staging
    state: present
  become_user: "{{ ansible_user }}"
